// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtualAssistant.Data.EntityFrameworkCore;

#nullable disable

namespace VirtualAssistant.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(VirtualAssistantDbContext))]
    [Migration("20251214145304_DropAgentMessagingTables")]
    partial class DropAgentMessagingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtualAssistant.Data.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_agents_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_name_unique");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.AgentTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ClaudeSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claude_session_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedByAgentId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_agent_id");

                    b.Property<int?>("GithubIssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("github_issue_number");

                    b.Property<string>("GithubIssueUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_issue_url");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<bool>("RequiresApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("requires_approval");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int?>("TargetAgentId")
                        .HasColumnType("integer")
                        .HasColumnName("target_agent_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAgentId");

                    b.HasIndex("GithubIssueNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_tasks_github_issue_number_unique")
                        .HasFilter("github_issue_number IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_agent_tasks_status");

                    b.HasIndex("TargetAgentId", "Status")
                        .HasDatabaseName("ix_agent_tasks_target_status");

                    b.ToTable("agent_tasks", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer")
                        .HasColumnName("repository_id");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "IssueNumber")
                        .IsUnique();

                    b.ToTable("github_issues", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("github_repositories", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.SystemStartup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GreetingSpoken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("greeting_spoken");

                    b.Property<DateTime?>("ShutdownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shutdown_at");

                    b.Property<string>("ShutdownType")
                        .HasColumnType("text")
                        .HasColumnName("shutdown_type");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("StartupType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("startup_type");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("system_startups", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.VoiceTranscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("SourceApp")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_app");

                    b.Property<string>("TranscribedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transcribed_text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("voice_transcriptions", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.AgentTask", b =>
                {
                    b.HasOne("VirtualAssistant.Data.Entities.Agent", "CreatedByAgent")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualAssistant.Data.Entities.Agent", "TargetAgent")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("TargetAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAgent");

                    b.Navigation("TargetAgent");
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubIssue", b =>
                {
                    b.HasOne("VirtualAssistant.Data.Entities.GitHubRepository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.Agent", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubRepository", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
