// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtualAssistant.Data.EntityFrameworkCore;

#nullable disable

namespace VirtualAssistant.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(VirtualAssistantDbContext))]
    [Migration("20251214161340_AddNotificationStatusWorkflow")]
    partial class AddNotificationStatusWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtualAssistant.Data.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_agents_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_name_unique");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer")
                        .HasColumnName("repository_id");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "IssueNumber")
                        .IsUnique();

                    b.ToTable("github_issues", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("github_repositories", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("NotificationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("notification_status_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_notifications_agent");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("NotificationStatusId")
                        .HasDatabaseName("ix_notifications_status");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.NotificationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_statuses_name_unique");

                    b.ToTable("notification_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NewlyReceived"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SentForSummarization"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Summarized"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SentForTranslation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Translated"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Announced"
                        },
                        new
                        {
                            Id = 8,
                            Name = "WaitingForPlayback"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Played"
                        });
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.SystemStartup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GreetingSpoken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("greeting_spoken");

                    b.Property<DateTime?>("ShutdownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shutdown_at");

                    b.Property<string>("ShutdownType")
                        .HasColumnType("text")
                        .HasColumnName("shutdown_type");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("StartupType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("startup_type");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("system_startups", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.VoiceTranscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("SourceApp")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_app");

                    b.Property<string>("TranscribedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transcribed_text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("voice_transcriptions", (string)null);
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubIssue", b =>
                {
                    b.HasOne("VirtualAssistant.Data.Entities.GitHubRepository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.Notification", b =>
                {
                    b.HasOne("VirtualAssistant.Data.Entities.Agent", "Agent")
                        .WithMany("Notifications")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualAssistant.Data.Entities.NotificationStatus", "Status")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.Agent", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.GitHubRepository", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("VirtualAssistant.Data.Entities.NotificationStatus", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
