// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Olbrasoft.VirtualAssistant.Data.EntityFrameworkCore;

#nullable disable

namespace Olbrasoft.VirtualAssistant.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(VirtualAssistantDbContext))]
    partial class VirtualAssistantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_agents_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_name_unique");

                    b.ToTable("agents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 6, 23, 11, 18, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Label = "agent:opencode",
                            Name = "opencode"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 6, 23, 11, 18, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Label = "agent:claude-code",
                            Name = "claude-code"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 6, 22, 43, 47, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Label = "agent:gemini",
                            Name = "gemini"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 15, 12, 40, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Label = "agent:antigravity",
                            Name = "antigravity"
                        });
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.GitHubIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer")
                        .HasColumnName("repository_id");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "IssueNumber")
                        .IsUnique();

                    b.ToTable("github_issues", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.GitHubRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("github_repositories", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.LlmCorrection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("corrected_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<int>("PromptId")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_id");

                    b.Property<int>("WhisperTranscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("whisper_transcription_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PromptId");

                    b.HasIndex("WhisperTranscriptionId");

                    b.ToTable("llm_corrections", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.LlmError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<int>("WhisperTranscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("whisper_transcription_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("WhisperTranscriptionId");

                    b.ToTable("llm_errors", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("FinalProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("final_provider_id");

                    b.Property<string>("FinalTtsStatus")
                        .HasColumnType("text")
                        .HasColumnName("final_tts_status");

                    b.Property<int>("NotificationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("notification_status_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("TtsCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tts_completed_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_notifications_agent");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("FinalProviderId")
                        .HasDatabaseName("ix_notifications_final_provider");

                    b.HasIndex("NotificationStatusId")
                        .HasDatabaseName("ix_notifications_status");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.NotificationGitHubIssue", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    b.Property<int>("GitHubIssueId")
                        .HasColumnType("integer")
                        .HasColumnName("github_issue_id");

                    b.HasKey("NotificationId", "GitHubIssueId");

                    b.HasIndex("GitHubIssueId")
                        .HasDatabaseName("ix_notification_github_issues_github_issue_id");

                    b.ToTable("notification_github_issues", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.NotificationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_statuses_name_unique");

                    b.ToTable("notification_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NewlyReceived"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SentForSummarization"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Summarized"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SentForTranslation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Translated"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Announced"
                        },
                        new
                        {
                            Id = 8,
                            Name = "WaitingForPlayback"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Played"
                        });
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.NotificationTtsAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptOrder")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_order");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notification_tts_attempts_created_at");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_notification_tts_attempts_notification");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_notification_tts_attempts_provider");

                    b.ToTable("notification_tts_attempts", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppIdPattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("app_id_pattern");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PromptFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prompt_file_name");

                    b.HasKey("Id");

                    b.HasIndex("AppIdPattern");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_providers_type");

                    b.HasIndex("Name", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_providers_name_type");

                    b.ToTable("providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 30, 22, 51, 45, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "AzureTTS",
                            Priority = 1,
                            Type = "tts"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 30, 22, 51, 45, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "EdgeTTS-WebSocket",
                            Priority = 2,
                            Type = "tts"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 30, 22, 51, 45, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "VoiceRSS",
                            Priority = 3,
                            Type = "tts"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 30, 22, 51, 45, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "GoogleTTS",
                            Priority = 4,
                            Type = "tts"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 30, 22, 51, 45, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "Piper",
                            Priority = 5,
                            Type = "tts"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 30, 22, 51, 45, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "cache",
                            Priority = 0,
                            Type = "tts"
                        });
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.SystemStartup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GreetingSpoken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("greeting_spoken");

                    b.Property<DateTime?>("ShutdownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shutdown_at");

                    b.Property<string>("ShutdownType")
                        .HasColumnType("text")
                        .HasColumnName("shutdown_type");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("StartupType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("startup_type");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("system_startups", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.TranscriptionCorrection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CaseSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("case_sensitive");

                    b.Property<string>("CorrectText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correct_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IncorrectText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("incorrect_text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("IncorrectText");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsActive", "Priority");

                    b.ToTable("transcription_corrections", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.TranscriptionCorrectionUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("context");

                    b.Property<int>("CorrectionId")
                        .HasColumnType("integer")
                        .HasColumnName("correction_id");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id");

                    b.HasIndex("CorrectionId")
                        .HasDatabaseName("ix_transcription_correction_usage_correction_id");

                    b.HasIndex("UsedAt")
                        .HasDatabaseName("ix_transcription_correction_usage_used_at");

                    b.ToTable("transcription_correction_usage", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.VoiceTranscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("SourceApp")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_app");

                    b.Property<string>("TranscribedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transcribed_text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("voice_transcriptions", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.WhisperTranscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudioDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("audio_duration_ms");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("TranscribedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("transcribed_text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("whisper_transcriptions", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.GitHubIssue", b =>
                {
                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.GitHubRepository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.LlmCorrection", b =>
                {
                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.Prompt", "Prompt")
                        .WithMany("LlmCorrections")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.WhisperTranscription", "WhisperTranscription")
                        .WithMany()
                        .HasForeignKey("WhisperTranscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");

                    b.Navigation("WhisperTranscription");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.LlmError", b =>
                {
                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.WhisperTranscription", "WhisperTranscription")
                        .WithMany()
                        .HasForeignKey("WhisperTranscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WhisperTranscription");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Notification", b =>
                {
                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.Agent", "Agent")
                        .WithMany("Notifications")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.Provider", "FinalProvider")
                        .WithMany()
                        .HasForeignKey("FinalProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.NotificationStatus", "Status")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("FinalProvider");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.NotificationGitHubIssue", b =>
                {
                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.Notification", "Notification")
                        .WithMany("NotificationGitHubIssues")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.NotificationTtsAttempt", b =>
                {
                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.Notification", "Notification")
                        .WithMany("TtsAttempts")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.Provider", "Provider")
                        .WithMany("TtsAttempts")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.TranscriptionCorrectionUsage", b =>
                {
                    b.HasOne("Olbrasoft.VirtualAssistant.Data.Entities.TranscriptionCorrection", "Correction")
                        .WithMany()
                        .HasForeignKey("CorrectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correction");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Agent", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.GitHubRepository", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Notification", b =>
                {
                    b.Navigation("NotificationGitHubIssues");

                    b.Navigation("TtsAttempts");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.NotificationStatus", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Prompt", b =>
                {
                    b.Navigation("LlmCorrections");
                });

            modelBuilder.Entity("Olbrasoft.VirtualAssistant.Data.Entities.Provider", b =>
                {
                    b.Navigation("TtsAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
