namespace Olbrasoft.VirtualAssistant.Core.Speech;

/// <summary>
/// Represents the result of speech transcription.
/// </summary>
public class TranscriptionResult
{
    /// <summary>
    /// Gets the transcribed text (final result after all processing).
    /// </summary>
    public string Text { get; }

    /// <summary>
    /// Gets the confidence score (0.0 to 1.0).
    /// </summary>
    public float Confidence { get; }

    /// <summary>
    /// Gets a value indicating whether transcription was successful.
    /// </summary>
    public bool Success { get; }

    /// <summary>
    /// Gets the error message if transcription failed.
    /// </summary>
    public string? ErrorMessage { get; }

    /// <summary>
    /// Gets the original text from Whisper before any filtering or LLM correction.
    /// Null if no processing was applied or if transcription failed.
    /// </summary>
    public string? OriginalText { get; init; }

    /// <summary>
    /// Gets the text after filtering but before LLM correction.
    /// Null if text filter was not applied or if transcription failed.
    /// </summary>
    public string? FilteredText { get; init; }

    /// <summary>
    /// Gets the duration of LLM correction in milliseconds.
    /// Null if LLM correction was not applied or if transcription failed.
    /// </summary>
    public int? LlmDurationMs { get; init; }

    /// <summary>
    /// Gets the ID of the prompt used for LLM correction.
    /// Null if LLM correction was not applied or if transcription failed.
    /// </summary>
    public int? PromptId { get; init; }

    /// <summary>
    /// Gets the ID of the LLM model used for correction.
    /// Null if LLM correction was not applied or if transcription failed.
    /// </summary>
    public int? ModelId { get; init; }

    /// <summary>
    /// Gets the ID of the STT provider that performed the transcription.
    /// Used for tracking which provider (Google, Whisper, etc.) was used.
    /// Null if provider tracking is not available.
    /// </summary>
    public int? SttProviderId { get; init; }

    /// <summary>
    /// Number of input/prompt tokens consumed by LLM correction.
    /// </summary>
    public int? InputTokens { get; init; }

    /// <summary>
    /// Number of output/completion tokens generated by LLM correction.
    /// </summary>
    public int? OutputTokens { get; init; }

    /// <summary>
    /// Number of reasoning tokens used by LLM correction (Mercury 2).
    /// </summary>
    public int? ReasoningTokens { get; init; }

    /// <summary>
    /// Initializes a new instance for successful transcription.
    /// </summary>
    public TranscriptionResult(string text, float confidence)
    {
        Text = text;
        Confidence = confidence;
        Success = true;
        ErrorMessage = null;
    }

    /// <summary>
    /// Initializes a new instance for failed transcription.
    /// </summary>
    public TranscriptionResult(string errorMessage)
    {
        Text = string.Empty;
        Confidence = 0.0f;
        Success = false;
        ErrorMessage = errorMessage;
    }
}
